sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.26.128
    port: 3307
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    dev:
      endpoint: oss-cn-beijing.aliyuncs.com
      access-key-id: LTAI5t8WQMWdvQwfBD71ysUD
      access-key-secret: VkoTTqIorNwPJCNmKpTNPu5HM1rove
      bucket-name: 15754